name: Test - PR

on: pull_request

env:
  previous_tag: ''
  new_tag: ''

jobs:
  build_test:
    runs-on: ubuntu-18.04

    outputs:
      previous_tag: ${{ steps.previous_tag.outputs.previous_tag }}
      new_tag: ${{ steps.new_tag.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "::set-output name=version::$(echo $(jq -r .version package.json))"
        id: version

      - name: Define s3ConfigPath
        run: echo "::set-output name=s3ConfigPath::$(echo test/config/${{ steps.version.outputs.version }}-0/config.json)"
        id: s3ConfigPath

      - name: Previous tag
        run: echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags)"
        id: previous_tag
      - name: New tag
        run: echo "::set-output name=new_tag::$(echo v${{ steps.version.outputs.version }})"
        id: new_tag

  tagging:
    runs-on: ubuntu-18.04
    needs: build_test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo tags
        run: echo "${{ needs.build_test.outputs.new_tag }} --- ${{ needs.build_test.outputs.previous_tag }}"
      - name: Tag release
        if: needs.build_test.outputs.new_tag > needs.build_test.outputs.previous_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: $NEW_TAG
          tag_prefix: ''
          dry_run: true
