name: Test - PR

on: pull_request

env:
  previous_tag: ''
  new_tag: ''

jobs:
  github_release:
    runs-on: ubuntu-latest
    needs: build_test

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "::set-output name=version::$(echo $(jq -r .version package.json))"
        id: version
      - name: Previous tag
        run: echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags)"
        id: previous_tag
      - name: New tag
        run: echo "::set-output name=new_tag::$(echo v${{ steps.version.outputs.version }})"
        id: new_tag

      - name: Tag release
        id: tag_release
        if: steps.new_tag.outputs.new_tag  > steps.previous_tag.outputs.previous_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.new_tag.outputs.new_tag  }}

      - name: Generate changelog
        if: steps.tag_release.outcome == 'success'
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: steps.tag_release.outcome == 'success'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.new_tag.outputs.new_tag }}
          name: "${{ github.event.repository.name }}-${{ steps.new_tag.outputs.new_tag }}"
          body: |
            Release ${{ steps.new_tag.outputs.new_tag }} includes the following commits:

            ${{ steps.changelog.outputs.changelog }}

  s3_release:
    runs-on: ubuntu-latest
    needs: github_release

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: echo "HELLO"
