name: Test - PR

on: pull_request

env:
  PREVIOUS_TAG: ''
  NEW_TAG: ''

jobs:
  build_test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "::set-output name=version::$(echo $(jq -r .version package.json))"
        id: version

      - name: Define s3ConfigPath
        run: echo "::set-output name=s3ConfigPath::$(echo test/config/${{ steps.version.outputs.version }}-0/config.json)"
        id: s3ConfigPath
      - name: Define artifactName
        run: echo "::set-output name=artifactName::$(echo blacksmith-${{ steps.version.outputs.version }}-0-linux-x64.tar.gz)"
        id: artifactName

      - name: Previous tag
        run: echo "git describe --abbrev=0 --tags" >> $PREVIOUS_TAG
      - name: New tag
        run: echo "v${{ steps.version.outputs.version }}" >> $NEW_TAG

  tagging:
    runs-on: ubuntu-18.04
    needs: build_test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag release
        if: $NEW_TAG > $PREVIOUS_TAG
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: $NEW_TAG
          tag_prefix: ''
          dry_run: true
