name: Test - PR

on: pull_request

jobs:
  build_test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "::set-output name=version::$(echo $(jq -r .version package.json))"
        id: version

      - name: Define s3ConfigPath
        run: echo "::set-output name=s3ConfigPath::$(echo test/config/${{ steps.version.outputs.version }}-0/config.json)"
        id: s3ConfigPath
      - name: Define artifactName
        run: echo "::set-output name=artifactName::$(echo blacksmith-${{ steps.version.outputs.version }}-0-linux-x64.tar.gz)"
        id: artifactName

      - name: Previous tag
        run: echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags)"
        id: previous_tag
      - name: New tag
        run: echo "::set-output name=new_tag::$(echo v${{ steps.version.outputs.version }})"
        id: new_tag
      - name: Echo versions
        run: echo "${{ steps.new_tag.outputs.new_tag }} ---- ${{ steps.previous_tag.outputs.previous_tag }}"
      - name: Tag release
        if: steps.new_tag.outputs.new_tag > steps.previous_tag.outputs.previous_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.new_tag.outputs.new_tag }}
          tag_prefix: ''
          dry_run: true
