name: Test - PR

on: pull_request

env:
  previous_tag: ''
  new_tag: ''

jobs:
  build_test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "::set-output name=version::$(echo $(jq -r .version package.json))"
        id: version

      - name: Define s3ConfigPath
        run: echo "::set-output name=s3ConfigPath::$(echo test/config/${{ steps.version.outputs.version }}-0/config.json)"
        id: s3ConfigPath

      - name: Previous tag
        run: echo "previous_tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: New tag
        run: echo "new_tag=v${{ steps.version.outputs.version }}" >> $GITHUB_ENV

  tagging:
    runs-on: ubuntu-18.04
    needs: build_test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo tags
        run: echo "${{ env.new_tag }} --- ${{ env.previous_tag }}"
      - name: Tag release
        if: env.new_tag > env.previous_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: $NEW_TAG
          tag_prefix: ''
          dry_run: true
